---
version: "3"
services:
  dnscrypt-proxy: &default
    build:
      context: dockerfiles/dnscrypt-proxy
      args:
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    image: bdossantos/dnscrypt-proxy
    container_name: dnscrypt-proxy
  paperless-ngx:
    <<: *default
    build:
      context: dockerfiles/paperless-ngx
      dockerfile: Dockerfile
    image: bdossantos/paperless-ngx
    container_name: paperless-ngx
  php-lol83:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.3
    image: bdossantos/php-lol83
    container_name: php-lol83
  php-lol84:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.4
    image: bdossantos/php-lol84
    container_name: php-lol84
  php-lol85:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.5
    image: bdossantos/php-lol85
    container_name: php-lol85
  php-lol83-rootless:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.3
      target: run-rootless
    image: bdossantos/php-lol83-rootless
    container_name: php-lol83-rootless
  php-lol84-rootless:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.4
      target: run-rootless
    image: bdossantos/php-lol84-rootless
    container_name: php-lol84-rootless
  php-lol85-rootless:
    <<: *default
    build:
      context: dockerfiles/php-lol
      dockerfile: Dockerfile.8.5
      target: run-rootless
    image: bdossantos/php-lol85-rootless
    container_name: php-lol85-rootless
  pingdom-exporter:
    <<: *default
    build:
      context: dockerfiles/pingdom-exporter
    image: bdossantos/pingdom-exporter
    container_name: pingdom-exporter
  pint:
    <<: *default
    build:
      context: dockerfiles/pint
    image: bdossantos/pint
    container_name: pint
  radicale:
    <<: *default
    build:
      context: dockerfiles/radicale
    image: bdossantos/radicale
    container_name: radicale
  resec:
    <<: *default
    build:
      context: dockerfiles/resec
    image: bdossantos/resec
    container_name: resec
  thumbor:
    <<: *default
    build:
      context: dockerfiles/thumbor
    image: bdossantos/thumbor
    container_name: thumbor
  tor:
    <<: *default
    build:
      context: dockerfiles/tor
    image: bdossantos/tor
    container_name: tor
  python-github-backup:
    <<: *default
    build:
      context: dockerfiles/python-github-backup
    image: bdossantos/python-github-backup
    container_name: python-github-backup
  memcached:
    <<: *default
    build:
      context: dockerfiles/memcached
    image: bdossantos/memcached
    container_name: memcached
  anki:
    <<: *default
    build:
      context: dockerfiles/anki
    image: bdossantos/anki
    container_name: anki
