#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DEBUG=${DEBUG:=0}
[[ $DEBUG -eq 1 ]] && set -o xtrace

DOCKERFILE=${1:-'dockerfiles/tor/Dockerfile'}

export \
  DOCKERFILE \

function main {
  DIRECTORY="$(dirname "$DOCKERFILE")"

  pushd "$DIRECTORY" >/dev/null
    # use parent directory as tag name
    TAG="${PWD##*/}"
    TAG="bdossantos/${TAG}"

    docker build -t "$TAG" .
  popd >/dev/null
}

main
