---
name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  discover:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      dockerfiles: ${{ steps.discover.outputs.dockerfiles }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
      - name: Discover Dockerfiles
        id: discover
        run: |
          dockerfiles=$(find dockerfiles -type f -name 'Dockerfile*' | sort | jq -R -s -c 'split("\n")[:-1]')
          echo "dockerfiles=${dockerfiles}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: discover
    strategy:
      matrix:
        dockerfile: ${{ fromJSON(needs.discover.outputs.dockerfiles) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
      - name: Build and push
        uses: ./.github/actions/docker
        with:
          dockerfile: ${{ matrix.dockerfile }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
