---
name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerfile:
          # FIXME: replace by a `find . -type f -name 'Dockerfile*'`
          - dockerfiles/anki/Dockerfile
          - dockerfiles/dnscrypt-proxy/Dockerfile
          #- dockerfiles/gcsfuse/Dockerfile
          - dockerfiles/paperless-ngx/Dockerfile
          - dockerfiles/php-lol/Dockerfile.8.1
          - dockerfiles/php-lol/Dockerfile.8.2
          - dockerfiles/pingdom-exporter/Dockerfile
          - dockerfiles/pint/Dockerfile
          - dockerfiles/python-github-backup/Dockerfile
          - dockerfiles/radicale/Dockerfile
          - dockerfiles/resec/Dockerfile
          - dockerfiles/thumbor/Dockerfile
          - dockerfiles/tor/Dockerfile
          - dockerfiles/twemproxy/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker
        with:
          dockerfile: ${{ matrix.dockerfile }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
